query initalData {
  userSettings {
    defaultShell
    workRoots {
      name
      path
      isDefault
    }
    tokenGenerator{
      customGrants{
        name
        parameters{
          label
          name
        }
      }
      identityServers
    }
  }

  appliation {
    workingDirectory
    configurationRequired
    version
  }
}
