
query searchRepos($input: SearchRepositoriesInput!){

  searchRepositories(input:$input){
    id
    name
    fullName
    url
    webUrl
    service
    {
      id
      name
      type
    }
  }

}