
trigger:
- main

resources:
- repo: self

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'yarn --cwd ./src/UI/boost-ui build'