
trigger:
- main

resources:
- repo: self

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'


stages:
- stage: Release
  displayName: Release
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Build_Tool
    displayName: Build Tool
    steps:
    - task: NuGetToolInstaller@1

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.sln'
        arguments: '-c Release'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'yarn --version'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'yarn --cwd ./src/UI/boost-ui build'