query version {
  version {
    installed
    packageId
    newerAvailable
    newerPreReleaseAvailable
    latest {
      published
      version
    }
    preRelease {
      published
      version
    }
  }
}
