query getIdentityRequest($id: UUID!) {
  identityRequest(id: $id) {
    id
    name
    modifiedAt
    createdAt
    tags
    type
    data {
      authority
      clientId
      secret
      grantType
      port
      scopes
      usePkce
      saveTokens
     parameters{
       name
       value
     }
    }
  }
}
