query snapshooter($withMismatchOnly: Boolean!) {
  snapshooterDirectories(withMismatchOnly: $withMismatchOnly) {
    name
    fullName
    snapshots {
      fileName
      hasMismatch
      missmatchFileName
      name
    }
  }
}